### ISSUE TITLE
Class member display

### ISSUE THREAD

**Issue by SadiqNacerodien** [avishkar58/primate#24]
When looking at members of a class, all members, teachers or anyone, looks the same. There is no way of telling whether it is a student, teacher, teacher aide etc...

Can we seperate these in the view and can they have different icons associated with the member type?

**Comment by avishkar58** [comment]
Assigned different icons to teachers and students. 
Also now ordering the member list on the structure editor, showing all teachers first ordered by name and then all students ordered by name.
